Add $PATH to drun

diff --git a/dmenu_drun b/dmenu_drun
--- a/dmenu_drun
+++ b/dmenu_drun
@@ -6,27 +6,26 @@
 # Modified by Tom van Dijk, now shows (unlocalized) names
 
 # associative array to store paths as basename values
-declare -A PATHS
+declare -gA PATHS
 
 # check we have required software
 if ! hash awk find grep dmenu gtk-launch &>/dev/null; then
-    echo -e "ERROR: This script requires: awk find grep dmenu" && exit 1
+    echo -e "ERROR: This script requires: awk find grep dmenu gtk-launch" && exit 1
 fi
 
 main() {
-    # base file name storage
-    local names=""
     while read -r f; do
-        name="$(cat "$f" | grep -E "^Name=" | sed -E 's/^Name=(.*)/\1/')"
-        n="$(basename -s .desktop "$f")"
+        name="$(grep -E "^Name=" "$f" | sed -E 's/^Name=(.*)/\1/')"
 
-        PATHS["$name"]="$n"
+        PATHS["$name"]="$f"
+    done < <(find -L /usr/share/applications/ $HOME/Desktop \
+        ~/.local/share/applications -type f -name '*.desktop')
 
-        names="$names
-$name"
-    done <<< "$(find -L /usr/share/applications/ $HOME/Desktop ~/.local/share/applications -type f -name '*.desktop')"
+    local ans="$(for key in "${!PATHS[@]}"; do echo "$key"; done \
+        | cat - <(dmenu_path) \
+        | uniq \
+        | dmenu -H $HOME/.dmenu_drun_histfile "$@")"
 
-    local ans="$(echo "$names" | sort | dmenu -H $HOME/.dmenu_drun_histfile "$@")"
     [[ $? != 1 && -n $ans ]] && run "$ans" || return 1
 }
 
@@ -34,7 +33,13 @@ run() {
     local cmd
     cmd="${PATHS["$1"]}"
 
-    gtk-launch "$cmd"
+    if [[ "$cmd" ]]; then
+        n="$(basename -s .desktop "$cmd")"
+        gtk-launch "$n"
+    else
+        exec "$1"
+    fi
+
     return $?
 }
 
